- hosts: localhost 
  become: True 
  tasks:
  - name: update
    apt:
      name: "*"
      state: latest

  - name: install docker dep
    apt:
      name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      state: latest
      update_cache: True   

  - name: add key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add rep
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install docker
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: True

  - name: activate service
    service:
      name: docker
      state: started
      enabled: True

  - name: config
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json

  - name: reboot docker
    service:
      name: docker
      state: restarted
